---
title: "New York Yankees: History of Wins & Homeruns"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
---

Inputs {.sidebar}
-----------------------------------------------------------------------
The New York Yankees are one of the most successful sports clubs in the world. The Yankees hold MLB records with 18 division titles, 40 American League pennants, and 27 World Series championships. These visualizations explore the relationship between homerun totals and wins throughout each year since 1913.


```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(Lahman)
library(ggplot2)

result<-Teams%>%
  filter(teamID=='NYA',yearID>1913)%>%
  select(yearID,SO,HR,W,L)

```

Row {data-height=450}
-----------------------------------------------------------------------

### Strikeouts vs Losses

```{r}
ggplot()+
  geom_point(data=result,aes(x=HR,y=W),color="navy",size=2)+
  xlab("Homeruns")+
  ylab("Wins")
```


### Win Distribution

```{r}
ggplot()+
  geom_histogram(data=result,aes(x=W),bins=10,color="white",fill="navy")+
  xlab("wins")
```

Row {data-height=550}
-----------------------------------------------------------------------

### Homerun Totals Through the Years

```{r}
ggplot()+
  geom_point(data=result,aes(x=yearID,y=HR),color="navy")+
  geom_line(data=result,aes(x=yearID,y=HR),color="navy")+
  xlab("year")+
  ylab("homeruns")
```

### Games Wons Through the Years

```{r}
ggplot()+
  geom_point(data=result,aes(x=yearID,y=W),color="navy")+
  geom_line(data=result,aes(x=yearID,y=W),color="navy")+
  xlab("year")+
  ylab("wins")
```

